---
# Eine NetworkPolicy, die allen eingehenen und ausgehenden Verkehr blockiert
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
name: default-deny
namespace: default
spec:
policyTypes:
- Ingress
- Egress
podSelector: {}
ingress: []
egress: []
