apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "helm-wordpress.fullname" . }}-secret"
type: Opaque
data:
  username: d3A=
  password: c2VjcmV0V3A=
  rootPassword: c3VwZXJTZWNyZXRQYXNzd29yZDEyMw==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "helm-wordpress.fullname" . }}-config"
data:
  WORDPRESS_DB_HOST:  "{{ include "helm-wordpress.fullname" . }}-db"
  WORDPRESS_DB_NAME: wp